import type { Metadata } from "next";
// import { Providers } from "@/providers";
import { Inter, Roboto_Mono } from "next/font/google";
import ToasterProvider from "@/providers/ToasterProvider";
import { AnnotationProvider } from "@/contexts/AnnotationContext";
import "./globals.css";
import { AnnotationHistoryProvider } from "@/contexts/AnnotationHistoryContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body className="antialiased">
        {/* <Providers>{children}</Providers> */}
        <AnnotationHistoryProvider>
          <AnnotationProvider>
            <ToasterProvider />
            {children}
          </AnnotationProvider>
        </AnnotationHistoryProvider>
      </body>
    </html>
  );
}
